// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVeaQHtztKD9XdhDOSyWC_byviqJJCt_Y',
    appId: '1:585529283508:web:f5056d5cdc39ae999518e1',
    messagingSenderId: '585529283508',
    projectId: 'safehaven-8403a',
    authDomain: 'safehaven-8403a.firebaseapp.com',
    storageBucket: 'safehaven-8403a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzfjraPJCwYzoH2CY_1MmIt8OKUVG9F0',
    appId: '1:585529283508:android:127306301fa050499518e1',
    messagingSenderId: '585529283508',
    projectId: 'safehaven-8403a',
    storageBucket: 'safehaven-8403a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_SZMkZXLdO2jqb_1AJEr_Mx26FCXVzA',
    appId: '1:585529283508:ios:e30d8aa3370c526b9518e1',
    messagingSenderId: '585529283508',
    projectId: 'safehaven-8403a',
    storageBucket: 'safehaven-8403a.firebasestorage.app',
    iosBundleId: 'com.example.safehaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_SZMkZXLdO2jqb_1AJEr_Mx26FCXVzA',
    appId: '1:585529283508:ios:e30d8aa3370c526b9518e1',
    messagingSenderId: '585529283508',
    projectId: 'safehaven-8403a',
    storageBucket: 'safehaven-8403a.firebasestorage.app',
    iosBundleId: 'com.example.safehaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVeaQHtztKD9XdhDOSyWC_byviqJJCt_Y',
    appId: '1:585529283508:web:7642abe35b83381a9518e1',
    messagingSenderId: '585529283508',
    projectId: 'safehaven-8403a',
    authDomain: 'safehaven-8403a.firebaseapp.com',
    storageBucket: 'safehaven-8403a.firebasestorage.app',
  );
}
